"""Public, versioned working-set capacity policy."""

MAX_ACTION_RECORDS = 256
MAX_ENERGY_RECORDS = 256
MAX_THOUGHT_BRANCHES = 256
MAX_MEMORY_RECORDS = 256
MAX_COGNITION_REFLECTIONS = 128
MAX_WORLD_PROPOSITIONS_PER_LAYER = 256
MAX_IDENTITY_ACTORS = 256
MAX_PROVENANCE_AUTHORIZATIONS = 256
MAX_PERSONALITY_VALUES_PER_LAYER = 2_048
MAX_RAW_LIFECYCLE_KEYS = 256
MAX_CAPABILITIES = 256
MAX_WORKSPACE_BROADCAST = 64

# An upper bound on collection records inspected by one frame projection.
# This intentionally counts repeated passes conservatively; it is independent
# of the immutable ledger's event count.
FRAME_PROJECTION_RECORD_BUDGET = (
    MAX_PERSONALITY_VALUES_PER_LAYER * 3 * 4
    + MAX_ENERGY_RECORDS * 3
    + MAX_WORKSPACE_BROADCAST * 3
    + MAX_THOUGHT_BRANCHES * 3
    + MAX_ACTION_RECORDS * 8
    + MAX_IDENTITY_ACTORS * 4
    + MAX_PROVENANCE_AUTHORIZATIONS * 2
    + MAX_MEMORY_RECORDS * 3
    + MAX_CAPABILITIES * 3
    + MAX_WORLD_PROPOSITIONS_PER_LAYER * 4 * 3
    + MAX_COGNITION_REFLECTIONS * 2
    + MAX_RAW_LIFECYCLE_KEYS * 2
)


__all__ = [
    "FRAME_PROJECTION_RECORD_BUDGET",
    "MAX_ACTION_RECORDS",
    "MAX_CAPABILITIES",
    "MAX_COGNITION_REFLECTIONS",
    "MAX_ENERGY_RECORDS",
    "MAX_IDENTITY_ACTORS",
    "MAX_MEMORY_RECORDS",
    "MAX_PERSONALITY_VALUES_PER_LAYER",
    "MAX_PROVENANCE_AUTHORIZATIONS",
    "MAX_RAW_LIFECYCLE_KEYS",
    "MAX_THOUGHT_BRANCHES",
    "MAX_WORKSPACE_BROADCAST",
    "MAX_WORLD_PROPOSITIONS_PER_LAYER",
]
